name: Update Contributions
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Update Contributions List
        run: |
          sed -i "$ a some text" README.md