name: Update Contributions
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Update Contributions List
        run: |
          # create the variables
          ACTOR="${{ github.actor }}"
          BOT="actions-user"
          
          # Function to check and add a contributor
          add_contributor_if_missing() {
            local username=$1
          
            local payload="<img src=\"https://github.com/${username}.png\" width=\"50\" height=\"50\" class=\"avatar avatar-user\" alt=\"${username}\">"
          
            if grep -q "alt=\"${username}\"" README.md; then
              echo "Contributor '${username}' is already present in README.md. Skipping."
            else
              echo "Contributor '${username}' side-by-side..."
              sed -i "s|.*Contributors.*|& ${payload}|" README.md
            fi
          }
          
          add_contributor_if_missing "$ACTOR"
          add_contributor_if_missing "$BOT"
          
          git add README.md
          if ! git diff --cached --quiet; then
            git config --local user.email "action@github.com"
            git config --local user.name "Github Action"
            git add README.md
            git commit -m "docs: update contributors in README"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No new contributors to add. Working tree clean."
          fi
