name: Update Contributions
on:
  push:
    branches:
      - main
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Update Contributions List
        run: |
          sed -i "$ a some text" README.md